config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show new create edit update destroy] do
    resources :friendships, only: %i[index create update destroy]
  end
  get 'list_user', to: "friendships#list_users", as: "list_users"
  get 'dashboard', to: "pages#index", as: :index
  get 'sortcollab', to: "pages#sortcollab", as: :sortcollab
  resources :trails, except: [:index] do
    member do
      get :list_activity
    end
    resources :activities, only: %i[index new create edit update destroy]
    resources :lists, only: %i[new create edit update destroy]
    resources :collabs, only: [:destroy]
  end

  # Creating api to fetch items from categories
  resources :categories, only: [:show] do
    resources :items, only: [:index]
  end

  resources :lists, only: [:show] do
    resources :list_items, only: [:update]
  end

  resources :list_items, only: [:show] do
    resources :delegations, only: [:create]
  end

  resources :activities, only: [:show]
  resources :list_items, only: [:destroy]
  resources :delegations, only: %i[update destroy]
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :trail

  has_many :list_items, dependent: :destroy
  has_many :items, through: :list_items

  validates :name, presence: true
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_trail, only: %i[new create edit update destroy]
  # before_action :set_activity, only: %i[show edit update destroy]
  before_action :set_list, only: %i[show edit update destroy]

  def show
    authorize @list
    @list_items = ListItem.where(list_id: @list.id).order(:id)
    @collabs = Collab.where(trail_id: @list.trail)
    @collabs = @collabs.map(&:user)
    @collabs = [@list.trail.user] + @collabs
    # uncomment for auto-check feature
    @list_items.each do |list_item|
      checked_count = list_item.delegations.where(checked: true).count
      all_count = list_item.delegations.all.count
      if checked_count == all_count && all_count != 0
        list_item.checked = true
      elsif !list_item.checked?
        list_item.checked = false
      end
    end
  end

  def new
    @list = List.new
    @list.trail = @trail
    authorize @list
    @categories = Category.all
  end

  def create
    @list = List.new(list_params)
    @list.trail = @trail
    authorize @list
    if @list.save
      # removes custom items from list
      params[:deletes]&.each do |item_name|
        item = Item.find_by(name: item_name)
        item.destroy
      end
      # creates list_items with templated and custom items
      params[:items]&.each do |item|
        # check if id is a number, then create listitem
        if item.to_i.positive?
          ListItem.create(item_id: item, list_id: @list.id)
        else
          list_item = ListItem.new(list_id: @list.id)
          category = Category.find(params[:list][:others][:category].to_i)
          item = Item.create(name: item, custom: true, user_id: current_user.id)
          ItemCategory.create(item_id: item.id, category_id: category.id)
          list_item.item = item
          list_item.save
        end
      end
      flash[:notice] = "List created!"
      redirect_to list_path(@list)
    else
      flash[:alert] = "Something went wrong!"
      render :new
    end
  end

  def edit
    authorize @list
  end

  def update
    authorize @list
    if @list.update(list_params)
      # Zache's code to filter selected items
      # edit_selecteds = params[:items].map { |item_id| item_id.to_i }
      # list_items = @list.list_items.map { |list_item| list_item.item_id }
      # edit_selecteds.reject { |edit_selected| list_items.include?(edit_selected) }

      # removes custom items from list
      params[:deletes]&.each do |item_name|
        item = Item.find_by(name: item_name)
        item.destroy
      end
      # creates list_items with templated and custom items
      params[:items]&.each do |item|
        # check if id is a number, then create listitem
        if item.to_i.positive?
          ListItem.create(item_id: item, list_id: @list.id)
        else
          list_item = ListItem.new(list_id: @list.id)
          category = Category.find(params[:list][:others][:category].to_i)
          item = Item.create(name: item, custom: true, user_id: current_user.id)
          ItemCategory.create(item_id: item.id, category_id: category.id)
          list_item.item = item
          list_item.save
        end
      end
      flash[:notice] = "List updated!"
      redirect_to list_path(@list)
    else
      flash[:alert] = "Something went wrong!"
      render :edit
    end
  end

  def destroy
    authorize @list
    @list.destroy
    redirect_to trail_path(@trail)
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def set_trail
    @trail = Trail.find(params[:trail_id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/views/lists/_delegation_list.html.erb
<% list_item.delegations&.each do |delegation| %>
  <div class="delegate <%= 'delegate-checked' if delegation.checked? %>">

    <%= link_to delegation_path(delegation.id), method: :delete, data: { confirm: "Remove delegation?" } do %>
      <% if delegation.user.photo.blank? %>
        <%= image_tag "placeholder.png", class: "avatar", crop: :fill %>
      <% else %>
        <%= cl_image_tag delegation.user.photo, class: "avatar", crop: :fill, gravity: :face %>
      <% end %>
    <% end %>

    <%= simple_form_for(delegation, url: delegation_path(delegation)) do |f| %>
      <% if delegation.user == current_user %>
        <% delegation_id = "delegate-check-#{delegation.list_item.id}" %>
        <%= f.input :checked, label: false, input_html: { class: "delegate-checkbox", id: delegation_id, onchange: "this.form.submit()" } %>
      <% else %>
        <%= f.input :checked, label: false, input_html: { class: "delegate-checkbox", disabled: true } %>
      <% end %>
    <% end %>
  </div>
<% end %>

<a href="#collabCollapse<%= list_item.id %>" data-toggle="collapse" aria-expanded="false" aria-controls="collabCollapse<%= list_item.id %>" >
  <i class="fas fa-user-plus ml-1"></i>
</a>

app/views/lists/_form.html.erb
<div class="form-navbar-offset">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <div class="form-template">
          <%= link_to :back do %>
            <i class="fas fa-arrow-circle-left fa-2x btn-back"></i>
          <% end %>
          <% if list.id %>
            <h1>Edit List</h1>
          <% else %>
            <h1>Create List</h1>
          <% end %>
          <%= simple_form_for [trail, list] do |f| %>
            <%= f.input :name, input_html: { class: "form-rounded mb-2" }, label: "List Name", placeholder: "e.g. Travel List" %>

            <%= f.simple_fields_for :others do |o| %>
              <%= o.input :category, label: "Select a category", as: :select, input_html: { class: "form-control select-category form-rounded" }, required: false,
                collection: ([Category.find_by(name: "Custom")] + Category.where.not(name: "Custom").order(:name)).map { |category| [category.name, category.id] }, selected: Category.find_by(name: "Custom").id %>
              <div class="custom-container">
                <%= o.input :custom_item, as: :string, label: false, input_html: { class: "custom-field form-rounded" }, required: false, placeholder: "e.g. Charger" %>
                <button type ="button" class="btn btn-info custom-btn">Add item</button>
              </div>
            <% end %>

            <h1 class="mb-0">What to bring?</h1>
            <div class="category-items">
            </div>

            <% if list.id %>
              <%= f.button :submit, "Edit list", id: "list-submit",class: "btn btn-info mb-3" %>
              <%= link_to "Delete", trail_list_path(@trail, list), method: :delete, data: { confirm: "Remove this list?" }, class: "btn btn-grey" %>
            <% else %>
              <%= f.button :submit, "Add list", class: "btn btn-info", id: "list-submit" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/lists/edit.html.erb
<%= render 'form', trail: @trail, list: @list %>
<%= render 'shared/bottomnav', list: @list %>

app/views/lists/new.html.erb
<%= render 'form', trail: @trail, list: @list %>
<%= render 'shared/bottomnav', list: @list %>

app/views/lists/show.html.erb
<div class="header">
  <div class="header-detail">
    <div class="header-title"><h3>Trail: </h3></div>
    <div class="header-name"><h3><%= @list.trail.name %></h3></div>
  </div>
  <div class="header-detail border-top pt-2">
    <div class="header-title"><h3>List: </h3></div>
    <div class="header-name"><h3><%= @list.name %></h3></div>
  </div>
  <div class="header-link">
    <%= link_to "Back to Trail", trail_path(@list.trail), class: "btn btn-info text-decoration-none" %>
    <%= link_to "Edit List", edit_trail_list_path(@list.trail), class: "btn btn-grey text-decoration-none" %>
  </div>
</div>

<div class="card-headers">
  <div class="card-item">
    <h2 class="ml-3">Item</h2>
    <div class="list-item-info mr-2">
      <h2>Qty</h2>
      <i class="fas fa-user-check"></i>
    </div>
  </div>
</div>

<div class="list-navbar-offset">
  <div style="height: 640px; overflow-y: scroll;">
    <% @list_items&.each_with_index do |list_item, index| %>
      <div class="card-items <%= 'checked' if list_item.checked? %>">
        <div class="card-item border-bottom">
          <h2><%= index + 1 %>. <%= list_item.item.name %></h2>
          <%= simple_form_for(list_item, url: list_list_item_path(@list, list_item)) do |f| %>
            <div class="list-item-info">
              <%= f.input :quantity, label: false, input_html: { class: "quantity", min: "0", max: "999", step: "1", onchange: "this.form.submit();" } %>
              <%= f.input :checked, label: false, input_html: { class: "checkbox", onchange: "this.form.submit();" } %>
            </div>
          <% end %>
        </div>

        <div class="card-item no-flex">
          <div data-delegation="<%= list_item.id %>" class="delegation-box">
            <%= render 'delegation_list', list_item: list_item, list: @list %>
          </div>
          <div class="list-item-buttons">
            <%= link_to "Remove", list_item_path(list_item), method: :delete, class: "btn-sm btn-grey" ,data: { confirm: "Remove item from list?" } %>
            <label for="delegate-check-<%= list_item.id %>" class="btn btn-sm btn-info mb-0">I brought this!</label>
          </div>
        </div>

        <div class="collabs collapse" id="collabCollapse<%= list_item.id %>">
          <h2 class="mb-1">Trail group (<%= @collabs.size %>)</h2>
          <% @collabs&.each do |collab_user| %>
            <%= link_to list_item_delegations_path(list_item, user_id: collab_user.id), method: :post, remote: :true do %>
              <% if collab_user.photo.blank? %>
                <%= image_tag "placeholder.png", class: "avatar", crop: :fill %>
              <% else %>
                <%= cl_image_tag collab_user.photo, class: "avatar", crop: :fill, gravity: :face %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render 'shared/bottomnav', list: @list %>