config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show new create edit update destroy] do
    resources :friendships, only: %i[index create update destroy]
  end
  get 'list_user', to: "friendships#list_users", as: "list_users"
  get 'dashboard', to: "pages#index", as: :index
  get 'sortcollab', to: "pages#sortcollab", as: :sortcollab
  resources :trails, except: [:index] do
    member do
      get :list_activity
    end
    resources :activities, only: %i[index new create edit update destroy]
    resources :lists, only: %i[new create edit update destroy]
    resources :collabs, only: [:destroy]
  end

  # Creating api to fetch items from categories
  resources :categories, only: [:show] do
    resources :items, only: [:index]
  end

  resources :lists, only: [:show] do
    resources :list_items, only: [:update]
  end

  resources :list_items, only: [:show] do
    resources :delegations, only: [:create]
  end

  resources :activities, only: [:show]
  resources :list_items, only: [:destroy]
  resources :delegations, only: %i[update destroy]
end

app/views/shared/_bottomnav.html.erb
<nav class="navbar fixed-bottom navbar-light bg-dark animated slideInUp">
  <div id="navimap">
    <% if controller_name == 'activities' %>
      <%= link_to "", trail_path(trail), class: "fas fa-arrow-circle-left text-decoration-none" %>
    <% elsif controller_name == 'lists' %>
      <%= link_to "", trail_activities_path(list.trail), class: "fas fa-map-marked-alt text-decoration-none" %>
    <% elsif controller_name == 'pages' || controller_name == 'friendships' %>
      <%= link_to "", edit_user_path(current_user), class: "fas fa-user-edit text-decoration-none" %>
    <% else %>
      <%= link_to "", trail_activities_path(trail), class: "fas fa-map-marked-alt text-decoration-none" %>
    <% end %>
  </div>
  <div id="navifriends">
    <% if controller_name != 'friendships' %>
      <%= link_to "", user_friendships_path(current_user), class: "fas fa-users text-decoration-none" %>
    <% end %>
  </div>
</nav>

<div id="navihome" class="fixed-bottom d-flex justify-content-center align-items-center animated slideInUp">
  <% if controller_name == 'pages' %>
    <%= link_to "", root_path, class: "fas fa-home text-decoration-none" %>
  <% else %>
    <%= link_to "", index_path, class: "fas fa-home text-decoration-none" %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>