config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show new create edit update destroy] do
    resources :friendships, only: %i[index create update destroy]
  end
  get 'list_user', to: "friendships#list_users", as: "list_users"
  get 'dashboard', to: "pages#index", as: :index
  get 'sortcollab', to: "pages#sortcollab", as: :sortcollab
  resources :trails, except: [:index] do
    member do
      get :list_activity
    end
    resources :activities, only: %i[index new create edit update destroy]
    resources :lists, only: %i[new create edit update destroy]
    resources :collabs, only: [:destroy]
  end

  # Creating api to fetch items from categories
  resources :categories, only: [:show] do
    resources :items, only: [:index]
  end

  resources :lists, only: [:show] do
    resources :list_items, only: [:update]
  end

  resources :list_items, only: [:show] do
    resources :delegations, only: [:create]
  end

  resources :activities, only: [:show]
  resources :list_items, only: [:destroy]
  resources :delegations, only: %i[update destroy]
end

app/models/trail.rb
class Trail < ApplicationRecord
  belongs_to :user

  has_many :lists, dependent: :destroy
  has_many :collabs, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :users, through: :collabs

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  before_action :set_trail, only: %i[show edit update destroy list_activity]

  def show
    authorize @trail
    @lists = List.where(trail_id: @trail.id)
    @activities = @trail.activities.group_by(&:date)
    range_dates = (@trail.start_date...@trail.end_date).to_a
    range_dates << @trail.end_date

    range_dates.each do |date|
      @activities[date] = [] if @activities[date].nil?
    end

    @activities = @activities.sort_by{|k, _extras| k }.to_h
  end

  def new
    @trail = Trail.new
    authorize @trail
  end

  def create
    @trail = Trail.new(trail_params)
    @trail.user = current_user
    authorize @trail
    if @trail.save
      if params[:trail][:others]
        collab_users_arr = params[:trail][:others][:email]
        create_collab(collab_users_arr, @trail)
      end
      flash[:notice] = "You created a new trail"
      redirect_to index_path
    else
      render :new
    end
  end

  def edit
    authorize @trail
  end

  def update
    authorize @trail
    if @trail.update(trail_params)
      if params[:trail][:others]
        collab_users_arr = params[:trail][:others][:email]
        create_collab(collab_users_arr, @trail)
      end
      flash[:notice] = "Trail info updated!"
      @trail.activities.all.each do |activity|
        activity.destroy if activity.date > @trail.end_date || activity.date < @trail.start_date
      end
      redirect_to index_path
    else
      flash[:alert] = "Something went wrong!"
      render :edit
    end
  end

  def destroy
    authorize @trail
    @trail.activities.destroy_all
    @trail.destroy
    redirect_to index_path
  end

  def list_activity
    authorize @trail
    @date = Date.parse(params[:date])
    @activities = @trail.activities.where(date: @date)
  end

  private

  def set_trail
    @trail = Trail.find(params[:id])
  end

  def trail_params
    params.require(:trail).permit(:name, :start_date, :end_date)
  end

  def create_collab(collab_users_arr, trail)
    collab_users_arr.each do |email|
      collab_user = User.find_by(email: email)
      if collab_user == trail.user
        flash[:alert] = "Cannot invite yourself!"
      elsif collab_user
        Collab.create(user_id: collab_user.id, trail_id: trail.id)
      else
        flash[:alert] = "This person is not your friend yet!"
      end
    end
  end
end

app/views/trails/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="form-template">
        <%= link_to :back do %>
          <i class="fas fa-arrow-circle-left btn-back"></i>
        <% end %>
        <%= simple_form_for trail do |f| %>
          <% if trail.id %>
            <h1>Trail info</h1>
          <% else %>
            <h1>Create Trail</h1>
          <% end %>

          <%= f.error_notification %>
          <%= f.input :name, input_html: { class: "form-rounded" }, label: "Trail name", placeholder: "e.g. Trail #{ Trail.count + 1 }" %>
          <%= f.input :start_date, input_html: { class: "form-rounded" } %>
          <%= f.input :end_date, input_html: { class: "form-rounded" } %>

          <%= f.simple_fields_for :others do |o| %>
            <%= o.input :email, input_html: { class: "form-control select2", multiple: "multiple" }, required: false,
              collection: current_user.friends.map { |user| [user.name, user.email] }, label: "Invite friends from your friends list", include_hidden: false %>
          <% end %>

          <% if trail.id %>
            <%= f.button :submit, "Update Trail", class: "btn btn-info" %>
            <%= link_to "Delete", trail_path(trail), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-grey mt-3" if trail.user == current_user %>
          <% else %>
            <%= f.button :submit, "Create Trail", class: "btn btn-info" %>
          <% end %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/trails/edit.html.erb
<div class="animated fadeIn">
  <%= render "form", trail: @trail %>
</div>

<%= render 'shared/bottomnav', trail: @trail%>

app/views/trails/list_activity.js.erb
function refreshForm(innerHTML) {
  const newActivityForm = document.getElementById('activity-form');
  newActivityForm.innerHTML = innerHTML;
}


var modalTitle = document.querySelector('#activity-modal-title')


modalTitle.innerText = '<%= @date.strftime("%A, %b %d")%>'


function displayCards(htmlCode){
  var modalBody = document.querySelector('#activity-modal-content')
    modalBody.innerHTML = htmlCode
}

 displayCards('<%= j render "activities/activities_list", activities: @activities, date: @date %>')



function addSweetAlert(){
  var swalButtons = document.querySelectorAll('.trigger-alert-button');
  console.log(swalButtons)
  swalButtons.forEach((btn)=>{
    btn.addEventListener('click', (e)=>{

      swal({
          title: "Are you sure?",
          text: "Once deleted, you will not be able to recover this imaginary file!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        }).then((value) => {
          if (value){
            var id = e.target.dataset.buttonId
            document.querySelector(`[data-link-id='${id}']`).click()
          }
        })

    })
  })

}


setTimeout(addSweetAlert, 1000)

app/views/trails/new.html.erb
<%= render 'form', trail: @trail %>

app/views/trails/original.html.erb
<div class="d-flex align-items-center" id="activity-horizontal-container" style="flex-wrap: nowrap; overflow: auto ">
  <%# date = @trail.start_date %>
  <%# until @trail.end_date + 1 == date %>
  <% @activities.each do |date, activities|%>




                <div class ="datecard" style = "flex: 0 0 auto">


                  <div class="card" style="width: 18rem; height:300px" >
                    <div class="card-body d-flex flex-column text-center justify-content-between">
                      <h5 class="card-title"><%#= date.strftime('%d %b %Y') %></h5>
                      <%# if array.empty? %>
                      <h1><%= date %></h1>
                      <h2 class="card-text"> NO ACTIVITIES TODAY! </h2>
                      <%# else %>
                      <% activities.take(2).each do |activity| %>
                      <div style= "border: 1px solid black">
                      <p class="card-text"><%= activity.name %></p>
                      <p class="card-text"><% activity.start_time %></p>
                      </div>
                      <% end %>
                      <%# end %>
                      <%= form_tag list_activity_trail_path(@trail), method: :get, remote:true do %>
                        <%= hidden_field_tag 'date', date %>
                        <button class="btn btn-primary" type="submit" data-toggle="modal" data-target="#exampleModalLong">See more</button>
                      <% end %>
                    </div>
                  </div>

                </div>

        <!-- Modal -->


  <%# date += 1 %>
  <% end %>
</div>
                      <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                          <div class="modal-content d-flex align-items-center" style= "position: relative">
                            <button type="button" class="close-modal-btn close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            <div class="modal-header">
                              <h2 class="modal-title" id="activity-modal-title"></h2>
                            </div>
                            <div id='activity-modal-content' class="modal-body">
                             </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                              <button type="button" class="btn btn-primary">Save changes</button>
                            </div>
                          </div>
                        </div>
                      </div>

app/views/trails/show.html.erb
<div class="header">
  <div class="header-detail">
    <div class="header-title"><h3>Trail: </h3></div>
    <div class="header-name"><h3><%= @trail.name %></h3></div>
  </div>
  <div class="border-top pt-2">
    <div class="header-date"><p class="text-muted"><%= @trail.start_date.strftime("%a, %b %d %Y") %> - <%= @trail.end_date.strftime("%a, %b %d %Y") %></p></div>
    <% if (@trail.start_date - Date.today).to_i > 0 %>
      <h5 class="text-muted">Countdown:</h5><h5>Trail begins in <%= (@trail.start_date - Date.today).to_i %> more days!</h5>
    <% elsif (@trail.start_date - Date.today).to_i == 0 %>
      <h5>First day of your trail! Have fun!</h5>
    <% elsif (@trail.end_date - @trail.start_date).to_i > 0 %>
      <h5><%= (@trail.end_date - Date.today).to_i %> more days left in this trail!</h5>
    <% else %>
      <h5 class="text-muted">This trail is completed!</h5>
    <% end %>
  </div>
</div>

<div class="trail-group">
  <h3 class="border-bottom pb-2">Trail group</h3>
  <p><%= @trail.users.count + 1 %> <%= "person".pluralize(@trail.users.count + 1) %> <%= "is".pluralize(@trail.users.count + 1) %> set for this trail!</p>
  <% if @trail.user.photo.blank? %>
    <%= image_tag "placeholder.png", class: "avatar", crop: :fill %>
  <% else %>
    <%= cl_image_tag @trail.user.photo, radius: :max, width: 40, height: 40, crop: :fill, gravity: :face %>
  <% end %>
  <% @trail.users.each do |collab_user| %>
    <% if current_user == @trail.user %>
      <%= link_to trail_collab_path(@trail, collab_user), method: :delete, data: { confirm: "Remove this friend from group?" }, class: "text-decoration-none" do %>
        <% if collab_user.photo.blank? %>
          <%= image_tag "placeholder.png", class: "avatar", crop: :fill %>
        <% else %>
          <%= cl_image_tag collab_user.photo, radius: :max, width: 40, height: 40, crop: :fill, gravity: :face %>
        <% end %>
      <% end %>
    <% else %>
      <% if current_user == collab_user %>
        <%= link_to trail_collab_path(@trail, collab_user), method: :delete, data: { confirm: "Remove myself from group?" }, class: "text-decoration-none" do %>
          <% if collab_user.photo.blank? %>
            <%= image_tag "placeholder.png", class: "avatar", crop: :fill %>
          <% else %>
            <%= cl_image_tag collab_user.photo, radius: :max, width: 40, height: 40, crop: :fill, gravity: :face %>
          <% end %>
        <% end %>
      <% else %>
        <% if collab_user.photo.blank? %>
          <%= image_tag "placeholder.png", class: "avatar", crop: :fill %>
        <% else %>
          <%= cl_image_tag collab_user.photo, radius: :max, width: 40, height: 40, crop: :fill, gravity: :face %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="trail-navbar-offset">
  <div class="card-headers d-flex flex-column justify-content-center pt-1">
    <h3>Planning <%= "List".pluralize(@trail.lists.count) %></h3>
    <p>There <%= "is".pluralize(@trail.lists.count) %> <%= @trail.lists.count %> <%= "list".pluralize(@trail.lists.count) %></p>
    <%= link_to new_trail_list_path(@trail), class: "list-add text-decoration-none" do %>
      <i class="fas fa-clipboard-check" style="font-size: 35px;"></i>
      <i class="fas fa-plus fa-lg"></i>
    <% end %>
  </div>

  <div class="activity-horizontal-container d-flex flex-row align-items-center" style="flex-wrap: nowrap; overflow: auto;">
    <% @lists&.each do |list| %>
      <div class ="list-card" style="flex: 0 0 auto;">
        <%= link_to list_path(list), class: "text-decoration-none" do %>
          <div class="list-name">
            <h3 class="text-muted"><%= list.name %></h3>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="card-headers d-flex flex-column justify-content-center pt-1">
    <h3>Activity <%= "Day".pluralize((@trail.end_date - @trail.start_date).to_i + 1) %></h3>
    <p><%= (@trail.end_date - @trail.start_date).to_i + 1 %> <%= "day".pluralize((@trail.end_date - @trail.start_date).to_i + 1) %> in this trail</p>
  </div>

  <div class="activity-horizontal-container d-flex align-items-center pb-5" style="flex-wrap: nowrap; overflow: auto;">
    <% @activities&.each do |date, activities|%>
      <div class ="datecard d-flex justify-content-center align-items-center" style = "flex: 0 0 auto;">
        <div data-id='card-container-<%= date.strftime('%Y-%m-%e') %>'class="d-flex justify-content-center" style="width: 18rem; height: 220px" >
          <%= render 'activities/small_card_content', activities: activities, date: date, trail: @trail %>
        </div>
      </div>
    <% end %>
    <div id="gap" class="pb-5">
    </div>
  </div>

  <div class="modal animated zoomIn" id="exampleModalLong"  tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog m-0 modal-dialog-centered" role="document">
      <div class="activity-modal-content modal-content d-flex align-items-center" style= "position: relative">
        <i class="far fa-times-circle" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"></span>
          </i>
        <div class="modal-header border-0 d-flex justify-content-center align-items-center t-5 mx-3">
          <i class="fas fa-calendar-day"></i>
          <h2 class="modal-title my-1 mx-2 py-3 " id="activity-modal-title"></h2>
        </div>
        <div id='activity-modal-content' class="d-flex flex-column modal-body">
         </div>
        <div class="modal-footer border-0">
          <button type="button" class="btn btn-info" style="color: black" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <%= render 'shared/bottomnav', trail: @trail %>
</div>