config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show new create edit update destroy] do
    resources :friendships, only: %i[index create update destroy]
  end
  get 'list_user', to: "friendships#list_users", as: "list_users"
  get 'dashboard', to: "pages#index", as: :index
  get 'sortcollab', to: "pages#sortcollab", as: :sortcollab
  resources :trails, except: [:index] do
    member do
      get :list_activity
    end
    resources :activities, only: %i[index new create edit update destroy]
    resources :lists, only: %i[new create edit update destroy]
    resources :collabs, only: [:destroy]
  end

  # Creating api to fetch items from categories
  resources :categories, only: [:show] do
    resources :items, only: [:index]
  end

  resources :lists, only: [:show] do
    resources :list_items, only: [:update]
  end

  resources :list_items, only: [:show] do
    resources :delegations, only: [:create]
  end

  resources :activities, only: [:show]
  resources :list_items, only: [:destroy]
  resources :delegations, only: %i[update destroy]
end

app/models/activity.rb
class Activity < ApplicationRecord
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  belongs_to :trail

  validates :name, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_trail, only: %i[index new create edit update destroy]
  before_action :set_activity, only: %i[show edit update destroy]

  def index
    @activities = policy_scope(Activity).geocoded # returns activities with coordinates
    authorize @activities
    @activities = @activities.where(trail_id: @trail.id)

    @markers = @activities.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { activity: activity }),
        image_url: helpers.asset_url('bluemarker.png')
      }
    end
  end

  def show
    @activity = Activity.find(params[:id])
    authorize @activity
  end

  def new
    @date = params[:date]
    @activity = Activity.new
    @activity.trail = @trail
    authorize @activity
    respond_to do |format|
      format.html { redirect_to trail_path(@trail) }
      format.js
    end
  end

  def create
    @trail = Trail.find(params[:trail_id])
    @activity = Activity.new(activity_params)
    @activity.date = params[:activity][:date]
    @activity.trail = @trail
    authorize @activity
    if @activity.save
      @activities = find_activities(@trail, @activity)
      respond_to do |format|
        format.html { redirect_to trail_path(@trail) }
        format.js
      end
    end
  end

  def edit
    authorize @activity
    respond_to do |format|
      format.html { redirect_to trail_path(@trail) }
      format.js
    end
  end

  def update
    @activity = Activity.find(params[:id])
    authorize @activity
    if @activity.update(activity_params)
      @activities = find_activities(@trail, @activity)
      respond_to do |format|
        format.html { redirect_to trail_path(@trail) }
        format.js
      end
    end
  end

  def destroy
    authorize @activity
    if @activity.destroy
      @activities = find_activities(@trail, @activity)
      respond_to do |format|
        format.html { redirect_to trail_path(@trail) }
        format.js
      end
    end
  end

  private

  def find_activities(trail, activity = nil)
    @activities = trail.activities.group_by(&:date)
    @activities = @activities[@activity.date]  || []
  end

  def set_trail
    @trail = Trail.find(params[:trail_id])
  end

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:start_time, :end_time, :name, :description, :location)
  end
end

app/views/activities/_activities_list.html.erb
  <% activities.each do |activity|  %>
      <%= render 'activities/card', activity: activity %>
  <% end %>
  <div class="modal-footer d-flex justify-content-center align-items-center border-0" >
    <%= form_tag new_trail_activity_path(@trail), method: :get, remote:true do %>
       <%= hidden_field_tag 'date', date %>
        <button type="submit" class="btn btn-info" id="plus"> Add an activity </button>
    <% end %>
  </div>
  <div id= "modal-form-box">
  </div>


<style>
  #plus {
    color:black;
    box-shadow: 0 0 8px rgba(0,0,0,0.1);
  }

</style>

app/views/activities/_card.html.erb
<div data-id=<%= activity.id %>>
    <div class="card">
           <div data-toggle="collapse" data-target="#collapse<%= activity.id %>" aria-expanded="true" aria-controls="collapse<%= activity.id %>" class="card-header shadow-sm p-0 mb-0 bg-white rounded" id="heading<%= activity.id %>" style="width: 22rem;" >

              <div class="card-body card-product d-flex justify-content-center align-items-center">
                  <div class="card-product-infos d-flex flex-column justify-content-center align-items-center ">
                    <h4><%= activity.name %></h4>
                  </div>
              </div>
            </div>

      <div id="collapse<%= activity.id %>" class="collapse hide" aria-labelledby="heading<%= activity.id %>" >
        <div class="card-body-1 p-3 d-flex justify-content-between">
          <div class="d-flex flex-column">
            <p><strong>Starting at: </strong><%= activity.start_time.to_datetime.strftime("%l:%M:%p") if activity.start_time != nil %></p>
            <p><strong>Ends by: </strong><%= activity.end_time.to_datetime.strftime("%l:%M:%p") if activity.end_time != nil %></p>
            <p>Location: <%= activity.location %></p>
            <p>Description: <%= activity.description %></p>
          </div>
          <div id="editdelete" class="d-flex justify-content-around align-items-start">
            <h1 class="btn btn-light d-flex justify-content-center align-items-center mx-1" style="height: 38px; width: 38px;"><%= link_to "", edit_trail_activity_path(activity.trail, activity), class: "fas fa-pencil-alt",  remote: true %></h1>

            <button data-button-id="<%= activity.id %>" class="trigger-alert-button btn btn-light fa fa-trash" style="height: 38px; width: 38px;  color: red"></button>
            <%= link_to trail_activity_path(activity.trail, activity), data:{'link-id': activity.id}, method: :delete, id:"sweet-alert-demo", class: " hidden", remote: true do %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  a {
    color: orange;
  }
  .btn-light {
    box-shadow: 0 0 10px #F5F5F5;
  }

</style>

app/views/activities/_form.html.erb
<div class="container d-flex flex-column p-0">
  <div class="form animated slideInUp">
    <%= simple_form_for [trail, activity], html: {id:"activity-form", data:{'activity-id-form': activity.id}} , remote: true do |f| %>
      <%= f.input :name, label: 'Activity' %>
      <%= f.hidden_field :date, as: :string, value: date %>
      <% if activity.id %>
        <div class="d-flex flex-column">
        <%= f.input :start_time, label: 'Start time', input_html: {class: "timepicker"} %>
        <%= f.input :end_time, label: 'End time', input_html: {class: "timepicker"} %>
        </div>
        <%= f.input :location %>
        <%= f.input :description %>
      <% end %>
      <div class="d-flex justify-content-center py-2 border-0">
      <%= f.button :submit, "Update Activity", class: "submit-btn-form btn btn-info" %>
      </div>
    <% end -%>
  </div>
</div>


<style>
  .btn-info {
    color: black;
  }

</style>

app/views/activities/_small_card_content.html.erb
<div class="card-body d-flex flex-column p-1 <%= activities.empty? ? 'justify-content-center': 'justify-content-between' %> text-center" style="height: 210px">
  <div>
    <h3 class="card-title"><%= date.strftime('%a, %b %d %Y')%></h3>
    <% if activities.empty? %>
      <div></div>
      <h3 class="text-muted">No Activities</h3>
      <%= form_tag list_activity_trail_path(@trail), method: :get, remote:true do %>
        <%= hidden_field_tag 'date', date %>
        <button class="modal-btn btn btn-info btn-sm btn-block" style="margin-top: 80px; type="submit" data-toggle="modal" data-target="#exampleModalLong">Add an activity</button>
      <% end %>
    <% elsif activities.count > 2 %>
      <% activities.take(2).each do |activity| %>
        <div class="card innercard m-1" style="border-radius: 5px; border: white; background-color: white;">
          <p class="card-innertext m-1"><%= activity.name %></p>
        </div>
      <% end %>
       <p>...</p>
       <div>
        <%= form_tag list_activity_trail_path(trail), method: :get, remote:true do %>
          <%= hidden_field_tag 'date', date %>
          <button class="modal-btn btn btn-info btn-sm btn-block" type="submit" data-toggle="modal" data-target="#exampleModalLong">See more</button>
        <% end %>
       </div>

    <% else %>
      <% activities.take(2).each do |activity| %>
        <div class="card innercard m-1" style="border-radius: 5px; border: white; background-color: white;">
          <p class="card-innertext m-1"><%= activity.name %></p>
        </div>
      <% end %>
    </div>
    <div>
      <%= form_tag list_activity_trail_path(trail), method: :get, remote:true do %>
        <%= hidden_field_tag 'date', date %>
        <button class="modal-btn btn btn-info btn-sm btn-block" type="submit" data-toggle="modal" data-target="#exampleModalLong">See more</button>
      <% end %>
    <% end %>
  </div>
</div>

<style>
  p {
    font-size: 1rem !important;
  }

</style>

app/views/activities/create.js.erb
function refreshForm(innerHTML) {
  const newActivityForm = document.getElementById('activity-form');
  newActivityForm.innerHTML = innerHTML;
}

function addActivity(activityHTML) {
  const activities = document.querySelector('.modal-footer');
  activities.insertAdjacentHTML('beforebegin', activityHTML);
}



var date = "card-container-<%= @activity.date.strftime('%Y-%m-%e')%>"
console.log(date)
var card = document.querySelector(`[data-id='${date}']`)
console.log(card)
function updateSmallCard(card, partial){
  card.innerHTML = partial
}


<% if @activity.errors.any? %>
refreshForm('<%= j render "activities/form", trail: @trail , activity: @activity, date: @activity.date  %>');
<% else %>
refreshForm('<%= j render "activities/form", trail: @trail , activity: Activity.new, date: @activity.date  %>');
addActivity('<%= j render "activities/card", activity: @activity %>');
updateSmallCard(card,  "<%= j render 'activities/small_card_content', activities: @activities, date: @activity.date, trail: @trail %>" )
if (document.querySelector("#activity-form")) document.querySelector("#activity-form").remove()
  function addSweetAlert(){
  var swalButtons = document.querySelectorAll('.trigger-alert-button');
  console.log(swalButtons)
  swalButtons.forEach((btn)=>{
    btn.addEventListener('click', (e)=>{
    var id = e.currentTarget.dataset.buttonId
      swal({
          title: "Are you sure?",
          text: "Delete this?",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        }).then((value) => {
          if (value){
            document.querySelector(`[data-link-id='${id}']`).click()
          }
        })

    })
  })

}


addSweetAlert()

<% end %>

app/views/activities/createoriginal.js.erb
function refreshForm(innerHTML) {
  const newActivityForm = document.getElementById('new_activity');
  newActivityForm.innerHTML = innerHTML;
}

function addActivity(activityHTML) {
  const activity = document.getElementById('activity-modal-content');
  activity.insertAdjacentHTML('beforeend', activityHTML);
}

<% if @review.errors.any? %>
  refreshForm('<%= j render "reviews/form", restaurant: @restaurant, review: @review %>');
<% else %>
  addReview('<%= j render "reviews/show", review: @review %>');
  refreshForm('<%= j render "reviews/form", restaurant: @restaurant, review: Review.new %>');
<% end %>

app/views/activities/destroy.js.erb
var currentCard = document.querySelector("[data-id='<%= @activity.id %>']")
currentCard.remove()
var date = "card-container-<%= @activity.date.strftime('%Y-%m-%e')%>"
console.log(date)
var card = document.querySelector(`[data-id='${date}']`)
console.log(card)
function updateSmallCard(card, partial){
  card.innerHTML = partial
}
updateSmallCard(card,  "<%= j render 'activities/small_card_content', activities: @activities, date: @activity.date, trail: @trail %>" )


if (document.querySelector("#activity-form")) document.querySelector("#activity-form").remove()

app/views/activities/edit.html.erb
<h1>Edit this activity</h1>

<%= render 'form', trail: @trail, activity: @activity %>

app/views/activities/index.html.erb
<div class="d-flex flex-column justify-content-center align-items-center text-center pt-2">
  <div class="loca d-flex justify-content-center align-items-center animated fadeIn delay-1s">
    <h3>LOCATIONS <i class="fas fa-location-arrow"></i></h3>
  </div>
  <div class="card animated zoomInDown" id="map" style="width: 99%;  height: 710px; width: 100vw;"  data-markers="<%= @markers.to_json %>"s data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

<%= render 'shared/bottomnav', trail: @trail %>

<style>
  .mapboxgl-ctrl-top-right {
      width: 94%;
  }

</style>

app/views/activities/new.html.erb
<%= render 'form', trail: @trail, activity: @activity %>

app/views/activities/new.js.erb
var activityForm = document.querySelector("[data-activity-id-form]")
if (activityForm){
  console.log (1);
  if (document.querySelector("#activity-form")) document.querySelector("#activity-form").remove()
  var formContainer = document.querySelector("#modal-form-box")
  formContainer.innerHTML = '<%= j render "activities/form", trail: @trail , activity: @activity, date: @date  %>';
}
  else {
    var addForm = document.querySelector("#activity-form")
    if (addForm){
      document.querySelector("#activity-form").remove()
      console.log (2);
    } else {
      var formContainer = document.querySelector("#modal-form-box")
      formContainer.innerHTML = '<%= j render "activities/form", trail: @trail , activity: @activity, date: @date  %>';
      console.log (3);
  }
}

app/views/activities/neworiginal.js.erb
if (document.querySelector("#activity-form")) document.querySelector("#activity-form").remove()
var formContainer = document.querySelector("#modal-form-box")
formContainer.innerHTML = '<%= j render "activities/form", trail: @trail , activity: @activity, date: @date  %>';

app/views/activities/show.html.erb
<h1><%= @activity.trail.name %></h1>
<p><%= @activity.start_time %> to <%= @activity.end_time %></p>

<p><%= @activity.description %></p>
<%= link_to "edit", edit_trail_activity_path(@activity.trail, @activity) %>

app/views/activities/update.js.erb
if (document.querySelector("#activity-form")) document.querySelector("#activity-form").remove()
var currentCard = document.querySelector("[data-id='<%= @activity.id %>']")
var container = document.querySelector('#activity-modal-content')
currentCard.insertAdjacentHTML('afterend', '<%= j render "activities/card", activity: @activity %>')
var date = "card-container-<%= @activity.date.strftime('%Y-%m-%e')%>"
console.log(date)
var card = document.querySelector(`[data-id='${date}']`)
console.log(card)
function updateSmallCard(card, partial){
  card.innerHTML = partial
}
updateSmallCard(card,  "<%= j render 'activities/small_card_content', activities: @activities, date: @activity.date, trail: @trail %>" )

currentCard.remove()